'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname,'..');
const read = file => fs.readFileSync(path.join(root,file),'utf8');
const json = file => JSON.parse(read(file));
const graph=json('skill-mistake-graph.json');
const transfer=json('bangla-english-transfer-graph.json');
const goals=json('goal-skill-requirements.json');
const destinations=json('smartpath-destinations.json');
const precis=read('precis-summary-writing-bangla.html');
const formal=read('formal-letter-writing-bangla.html');
const surface=read('common-mistakes-bangladeshi-learners.html');
const foundation=read('learning-foundation.js');
assert.equal(graph.graph_version,2); assert.equal(graph.families.length,11); assert.equal(graph.skills.length,52); assert.equal(graph.item_mappings.length,30);
assert.ok(graph.families.some(x=>x.family_id==='WRITING'));
assert.deepEqual(new Set(['writing_precis','formal_letter_writing']),new Set(graph.skills.filter(x=>x.family_id==='WRITING').map(x=>x.id)));
assert.equal(transfer.edges.length,4); assert.equal(goals.goal_ids.length,6); assert.equal(destinations.destinations.length,2);
assert.match(precis,/name="ovidhan:skill"[^>]+skill:writing_precis|content="skill:writing_precis" name="ovidhan:skill"/);
assert.match(formal,/content="skill:formal_letter_writing" name="ovidhan:skill"/);
assert.match(surface,/id="smartPath"/); assert.match(surface,/smartpath-router\.js/);
assert.match(surface,/id="smartPathGoal"/);
assert.equal(goals.mappings.filter(x=>x.goal_id==='BCS'&&['writing_precis','formal_letter_writing'].includes(x.skill_id)&&x.importance==='CORE').length,2);
assert.match(read('mistake-profile.js'),/shouldRenderLegacyNext/);
assert.match(foundation,/getRoutingGoal/); assert.match(foundation,/GENERAL_ENGLISH/);
assert.doesNotMatch([read('smartpath-router.js'),surface,foundation].join('\n'),/raw_writing|learner_textarea|audio_transcript/i);
console.log(JSON.stringify({status:'PASS',graph:{families:11,skills:52,itemMappings:30},transferPatterns:4,goals:6,writingDestinations:2},null,2));
