'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const pack = require('../data/bcs-written-smartpath-v1.json');
const grammarPack = require('../data/bcs-smartpath-practice-v1.json');
const literaturePack = require('../data/bcs-literature-smartpath-v1.json');
const graph = require('../skill-mistake-graph.json');
const goals = require('../goal-skill-requirements.json');
const mirror = require('../mistake-mirror.js');
const profile = require('../mistake-profile.js');
const router = require('../smartpath-router.js');
const learningApi = require('../learning-foundation.js');
const transferGraph = require('../bangla-english-transfer-graph.json');
const destinationGraph = require('../smartpath-destinations.json');

const allowed = new Set(['reading_main_idea','reading_supporting_detail','reading_inference','reading_tone_purpose','reading_reference','translation_bn_to_en','translation_en_to_bn','essay_thesis_focus','essay_outline_structure']);
const comprehension = pack.items.filter(item => item.candidate_id.startsWith('bcs-written-comp-'));
const translation = pack.items.filter(item => item.candidate_id.startsWith('bcs-written-trans-'));
const essay = pack.items.filter(item => item.candidate_id.startsWith('bcs-written-essay-'));
assert.equal(pack.pack_id, 'bcs-written-english-comprehension-translation-essay-v1');
assert.equal(pack.review_status, 'REVIEWED');
assert.deepEqual(pack.counts, {total:60,comprehension:24,translation:20,essay:16});
assert.equal(pack.items.length, 60); assert.equal(comprehension.length, 24); assert.equal(translation.length, 20); assert.equal(essay.length, 16);
assert.equal(pack.passages.length, 6);
pack.passages.forEach(passage => { const words = passage.text.trim().split(/\s+/).length; assert.equal(words, passage.word_count); assert.ok(words >= 220 && words <= 320); });
assert.equal(translation.filter(item => item.direction === 'BANGLA_TO_ENGLISH').length, 10);
assert.equal(translation.filter(item => item.direction === 'ENGLISH_TO_BANGLA').length, 10);
assert.equal(new Set(pack.items.map(item => item.candidate_id)).size, 60);
assert.deepEqual(new Set(pack.items.map(item => item.skill_id)), allowed);
comprehension.forEach(item => { assert.equal(item.options.length, 4); assert.equal(new Set(item.options.map(option => option.id)).size, 4); assert.equal(new Set(item.options.map(option => option.text)).size, 4); assert.equal(item.options.filter(option => option.id === item.correct_option).length, 1); });
translation.forEach(item => { const words = item.source_text.trim().split(/\s+/).length; assert.ok(words >= 35 && words <= 70); assert.ok(item.genuine_errors_bn.length); assert.ok(item.acceptable_alternatives.length); assert.equal(Object.hasOwn(item, 'common_errors_bn'), false); });
pack.items.forEach(item => { assert.equal(item.official_question, false); assert.equal(item.practice_type, 'OVIDHAN_CREATED_BCS_STYLE'); assert.equal(item.research_status, 'REVIEWED'); });
assert.equal(translation.filter(item => item.genuine_errors_bn.length).length, 20);
assert.equal(translation.filter(item => item.acceptable_alternatives.length).length, 20);
assert.equal(translation.filter(item => Object.hasOwn(item, 'common_errors_bn')).length, 0);

assert.equal(graph.families.length, 14); assert.equal(graph.skills.length, 65);
assert.equal(graph.skills.filter(skill => skill.status === 'ACTIVE').length, 65);
assert.equal(graph.skills.filter(skill => skill.status === 'PLANNED').length, 0);
assert.equal(graph.item_mappings.length, 240);
const oldMappings = graph.item_mappings.filter(mapping => !mapping.item_id.startsWith('bcs-written-'));
assert.equal(oldMappings.length, 180); assert.equal(oldMappings.filter(x=>x.item_id.startsWith('mm-')).length,30); assert.equal(oldMappings.filter(x=>x.item_id.startsWith('bcs-smartpath-')).length,70); assert.equal(oldMappings.filter(x=>x.item_id.startsWith('bcs-lit-candidate-')).length,80);
const newMappings = graph.item_mappings.filter(mapping => mapping.item_id.startsWith('bcs-written-'));
assert.equal(newMappings.length, 60); assert.equal(new Set(newMappings.map(mapping => mapping.item_id)).size, 60);
assert.ok(newMappings.every(mapping => allowed.has(mapping.primary_skill_id) && pack.items.some(item => item.candidate_id === mapping.item_id && item.skill_id === mapping.primary_skill_id)));
const skillIds = new Set(graph.skills.map(skill => skill.id)); graph.item_mappings.forEach(mapping => assert.ok(skillIds.has(mapping.primary_skill_id)));
assert.equal(graph.families.find(f=>f.family_id==='READING_COMPREHENSION').child_skill_ids.length,5);
assert.equal(graph.families.find(f=>f.family_id==='TRANSLATION').child_skill_ids.length,2);
assert.ok(graph.families.find(f=>f.family_id==='WRITING').child_skill_ids.includes('essay_thesis_focus'));
assert.ok(graph.families.find(f=>f.family_id==='WRITING').child_skill_ids.includes('essay_outline_structure'));
const newGoalMappings = goals.mappings.filter(mapping => allowed.has(mapping.skill_id));
assert.equal(newGoalMappings.length, 9); assert.ok(newGoalMappings.every(mapping => mapping.goal_id === 'BCS' && mapping.importance === 'CORE'));

mirror.addReviewedPack(grammarPack); mirror.addLiteraturePack(literaturePack); mirror.addWrittenPack(pack);
assert.equal(mirror.items.length, 240);
const writtenItems = mirror.items.filter(item => item.id.startsWith('bcs-written-'));
const productive = writtenItems.filter(item => item.type === 'guided-translation' || item.type === 'guided-essay');
assert.equal(productive.length, 36); assert.ok(productive.every(item => !Object.hasOwn(item,'correct') && !Object.hasOwn(item,'correct_option')));
const allDestinations = router.mistakeDestinations(mirror.items, graph).concat(destinationGraph.destinations);
assert.equal(allDestinations.filter(item=>item.item_id && item.item_id.startsWith('bcs-written-')).length,60);
const NOW = Date.parse('2026-08-22T12:00:00Z');
const run = (state, destinations=allDestinations) => router.recommend({state:Object.assign({goal:'BCS',level:null,mistakeSignals:{},recentActions:[]},state),profile:profile.aggregate(mirror.items,state,graph),graph,transferGraph,goalGraph:goals,destinations,nowMs:NOW});
['reading_main_idea','translation_bn_to_en','translation_en_to_bn','essay_thesis_focus','essay_outline_structure'].forEach(skill => { const result = run({}, allDestinations.filter(item=>item.skill_id===skill)); assert.equal(result.skill_id, skill); });
const signal = overrides => Object.assign({attempts:1,initialResult:null,repairResult:null,retestResult:null,initialCorrect:0,initialIncorrect:0,repairCorrect:0,repairIncorrect:0,retestCorrect:0,retestIncorrect:0}, overrides);
assert.equal(run({mistakeSignals:{'bcs-written-comp-024':signal({retestResult:'incorrect',retestIncorrect:1})}}).item_id,'bcs-written-comp-024');
assert.equal(run({mistakeSignals:{'bcs-written-comp-023':signal({initialResult:'incorrect',initialIncorrect:1})}}).item_id,'bcs-written-comp-023');
const firstProductive = run({}, allDestinations.filter(item=>item.activity_type==='GUIDED_TRANSLATION'));
const afterCompletion = run({recentActions:[{id:'mistake-mirror:'+firstProductive.item_id,type:'guided-productive-practice',result:null,at:'2026-08-22T11:00:00Z'}]}, allDestinations.filter(item=>item.activity_type==='GUIDED_TRANSLATION'));
assert.notEqual(afterCompletion.item_id, firstProductive.item_id);
['IELTS','BANK','UNIVERSITY_ADMISSION','GENERAL_ENGLISH','SPOKEN_CAREER'].forEach(goal => assert.ok(run({goal}).ranked_diagnostics.every(candidate => !String(candidate.item_id).startsWith('bcs-written-'))));

const storage = learningApi.createMemoryStorage(); const learning = learningApi.createLearningFoundation({localStorage:storage,sessionStorage:learningApi.createMemoryStorage(),crypto:{randomUUID:()=> '50000000-0000-4000-8000-000000000003'},now:()=>new Date('2026-08-22T12:00:00Z'),location:{hostname:'localhost',pathname:'/test',search:''}});
learning.recordLearningAction('mistake-mirror:bcs-written-trans-001','guided-productive-practice',null);
const state = learning.getState(); assert.equal(state.recentActions.at(-1).result,null); assert.equal(state.mistakeSignals['bcs-written-trans-001'],undefined); assert.equal(profile.aggregate(mirror.items,state,graph).observedItemCount,0);
const runtime = [read('mistake-mirror.js'),read('mistake-profile.js'),read('smartpath-router.js'),read('learning-foundation.js')].join('\n');
assert.doesNotMatch(read('mistake-mirror.js'), /guidedResponse[^\n]*(\.value|localStorage|sessionStorage)|localStorage|sessionStorage/);
assert.doesNotMatch(runtime, /fetch\(['"]https?:|XMLHttpRequest|api\.openai|openai\.com/i);
assert.doesNotMatch(runtime, /written_(learner_)?(store|profile|router)|secondLearner|secondProfile/i);
assert.equal((read('mistake-mirror.js').match(/\/data\/bcs-written-smartpath-v1\.json/g)||[]).length,1);
assert.equal(JSON.stringify(pack).includes('common_errors_bn'),false);

console.log(JSON.stringify({status:'PASS',activities:{total:60,comprehension:24,translation:20,essay:16},directions:{bnToEn:10,enToBn:10},passages:6,graph:{families:14,skills:65,active:65,planned:0,mappings:240,preservedMappings:180},bcsCoreMappings:9,productiveUngraded:36},null,2));
