'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const crypto = require('node:crypto');
const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const diagnostic = read('ielts-diagnostic.html');
const asset = require('../data/ielts-boundary-probes-v1.json');
const manifest = require('../data/ielts-diagnostic-skill-map-v1.json');
const graph = require('../skill-mistake-graph.json');
const questionMatch = diagnostic.match(/const QUESTIONS = (\[[\s\S]*?\]);\r?\nconst SKILLS/);
assert.ok(questionMatch, 'QUESTIONS literal missing');
const questions = vm.runInNewContext(questionMatch[1]);
const questionSha = crypto.createHash('sha256').update(JSON.stringify(questions)).digest('hex');
const expectedSha = '8885fda5188fe35301cda2ed2bdbeb255c460470b58c6cac544e4b31a9a8455d';
const expectedAnchors = ['ielts-diag-v1-q06', 'ielts-diag-v1-q08', 'ielts-diag-v1-q07', 'ielts-diag-v1-q25'];
const expectedProbeIds = ['ielts-boundary-v1-p01', 'ielts-boundary-v1-p02', 'ielts-boundary-v1-p03', 'ielts-boundary-v1-p04'];
const expectedEvidenceIds = ['ielts-boundary-v1:p01', 'ielts-boundary-v1:p02', 'ielts-boundary-v1:p03', 'ielts-boundary-v1:p04'];

assert.equal(questions.length, 40);
assert.equal(questionSha, expectedSha);
assert.equal(asset.schema_version, 1);
assert.equal(asset.pilot_id, 'ielts-boundary-v1');
assert.equal(asset.anchor_assessment_id, 'ielts-diagnostic-v1');
assert.equal(asset.anchor_question_set_sha256, expectedSha);
assert.equal(asset.evidence_type, 'BOUNDARY_PROBE');
assert.equal(asset.review_status, 'REVIEWED');
assert.equal(asset.probes.length, 4);
assert.deepEqual(asset.probes.map(probe => probe.probe_id), expectedProbeIds);
assert.deepEqual(asset.probes.map(probe => probe.evidence_id), expectedEvidenceIds);
assert.deepEqual(asset.probes.map(probe => probe.anchor_question_id), expectedAnchors);
assert.equal(new Set(asset.probes.map(probe => probe.probe_id)).size, 4);
assert.equal(new Set(asset.probes.map(probe => probe.evidence_id)).size, 4);
assert.ok(asset.probes.every(probe => probe.review_status === 'REVIEWED' && probe.scored === false));
assert.ok(asset.probes.every(probe => Number.isInteger(probe.correct_index) && probe.correct_index >= 0 && probe.correct_index < probe.options.length));
const questionIds = new Set(questions.map((_, index) => `ielts-diag-v1-q${String(index + 1).padStart(2, '0')}`));
assert.ok(asset.probes.every(probe => questionIds.has(probe.anchor_question_id)));
assert.ok(asset.probes.every(probe => !questionIds.has(probe.probe_id)));
const mapById = new Map(manifest.items.map(item => [item.question_id, item]));
asset.probes.forEach(probe => {
  const mapping = mapById.get(probe.anchor_question_id);
  assert.ok(mapping, `missing mapping ${probe.anchor_question_id}`);
  assert.equal(mapping.mapping_status, 'MAPPED_OBJECTIVE');
  assert.equal(mapping.primary_skill_id, probe.primary_skill_id);
});
assert.equal(graph.families.length, 14);
assert.equal(graph.skills.filter(skill => skill.status === 'ACTIVE').length, 65);
assert.equal(graph.item_mappings.length, 240);
assert.match(diagnostic, /deriveBoundarySignal\(anchorCorrect,probeCorrect\)/);
assert.match(diagnostic, /buildBoundaryEvidencePayload\(true\)/);
assert.match(diagnostic, /function showResults\(\)[\s\S]*buildBoundaryEvidencePayload\(true\)/);
assert.doesNotMatch(diagnostic.match(/function selectBoundaryAnswer[\s\S]*?function selectAnswer/)[0], /recordSkillEvidence/);
assert.match(diagnostic, /state\?\.status==='ANSWERED'/);
assert.doesNotMatch(diagnostic, /repairResult|retestResult|masteryStatus/);
assert.deepEqual([...diagnostic.matchAll(/['"](ovidhan_ielts_[^'"]+)['"]/g)].map(match => match[1]), ['ovidhan_ielts_diagnostic_v2']);
const frozen = require('../reports/ovidhan-learning-foundation-3b-frozen-hashes.json');
assert.equal(frozen.aggregateSha256, '202cc8c85317ff57756c7167b1bfb1c99f784497525f3fb633d2c81757148ce0');
[...frozen.pages, ...frozen.guards].forEach(item => assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root, item.path))).digest('hex'), item.sha256));
console.log(JSON.stringify({status: 'PASS', questions: 40, probes: 4, questionSetSha256: questionSha, graph: {families: 14, activeSkills: 65, itemMappings: 240}, frozenAggregateSha256: frozen.aggregateSha256}, null, 2));
