const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const crypto=require('node:crypto');
const root=path.join(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const graph=require('../skill-mistake-graph.json');
const manifest=require('../data/ielts-diagnostic-skill-map-v1.json');
const destinations=require('../smartpath-destinations.json').destinations;
const foundationApi=require('../learning-foundation.js');
const diagnostic=read('ielts-diagnostic.html');
const questionMatch=diagnostic.match(/const QUESTIONS = (\[[\s\S]*?\]);\r?\nconst SKILLS/);
assert.ok(questionMatch);
const diagnosticRuntime=diagnostic.match(/<script>\s*const QUESTIONS[\s\S]*?<\/script>/);
assert.ok(diagnosticRuntime);
new vm.Script(diagnosticRuntime[0].replace(/^<script>|<\/script>$/g,''));
const questions=vm.runInNewContext(questionMatch[1]);
const questionSetSha256=crypto.createHash('sha256').update(JSON.stringify(questions)).digest('hex');
const expectedIds=Array.from({length:40},(_,i)=>`ielts-diag-v1-q${String(i+1).padStart(2,'0')}`);
assert.equal(questions.length,40);
assert.match(diagnostic,/QUESTIONS\.forEach\(\(item,index\)=>\{item\.id=/);
assert.equal(manifest.schema_version,1);
assert.equal(manifest.assessment_id,'ielts-diagnostic-v1');
assert.equal(manifest.review_status,'REVIEWED');
assert.equal(manifest.practice_type,'OVIDHAN_CREATED_DIAGNOSTIC');
assert.equal(manifest.official_question,false);
assert.equal(manifest.question_set_sha256,questionSetSha256);
assert.equal(manifest.items.length,40);
assert.deepEqual(manifest.items.map(item=>item.question_id),expectedIds);
assert.equal(new Set(manifest.items.map(item=>item.question_id)).size,40);
assert.ok(manifest.items.every(item=>item.review_status==='REVIEWED'));
assert.ok(manifest.items.every((item,index)=>item.broad_category===questions[index].skill));
const allowedStatuses=new Set(['MAPPED_OBJECTIVE','UNMAPPED_PROXY','UNMAPPED_NO_CANONICAL_SKILL','UNMAPPED_PRODUCTIVE_CONSTRUCT']);
assert.ok(manifest.items.every(item=>allowedStatuses.has(item.mapping_status)));
const skillIds=new Set(graph.skills.map(skill=>skill.id));
const mapped=manifest.items.filter(item=>item.mapping_status==='MAPPED_OBJECTIVE');
const unmapped=manifest.items.filter(item=>item.mapping_status!=='MAPPED_OBJECTIVE');
assert.equal(mapped.length,19);
assert.equal(unmapped.length,21);
assert.equal(new Set(mapped.map(item=>item.primary_skill_id)).size,12);
assert.ok(mapped.every(item=>skillIds.has(item.primary_skill_id)&&item.evidence_type==='DIAGNOSTIC_OBJECTIVE'));
assert.ok(unmapped.every(item=>item.primary_skill_id===null&&item.evidence_type===null));
const byQuestion=new Map(manifest.items.map(item=>[item.question_id,item]));
['q12','q14','q19','q26','q30'].forEach(suffix=>assert.notEqual(byQuestion.get(`ielts-diag-v1-${suffix}`).mapping_status,'MAPPED_OBJECTIVE'));
assert.equal(byQuestion.get('ielts-diag-v1-q18').primary_skill_id,'reading_main_idea');
assert.ok(manifest.items.filter(item=>['listening','speaking'].includes(item.broad_category)).every(item=>item.mapping_status==='UNMAPPED_PROXY'&&item.primary_skill_id===null));
assert.equal(graph.families.length,14);
assert.equal(graph.skills.length,65);
assert.equal(graph.skills.filter(skill=>skill.status==='ACTIVE').length,65);
assert.equal(graph.item_mappings.length,240);
assert.match(diagnostic,/recordSkillEvidence\(/);
assert.doesNotMatch(diagnostic,/recordMistakeSignal\(/);
assert.match(diagnostic,/if\(current===QUESTIONS\.length-1\)showResults\(\)/);
assert.match(diagnostic,/setGoal\('IELTS'\)/);
assert.match(diagnostic,/Continue with IELTS SmartPath/);
assert.ok(!destinations.find(item=>item.skill_id==='writing_precis').goal_ids.includes('IELTS'));
assert.ok(destinations.find(item=>item.skill_id==='formal_letter_writing').goal_ids.includes('IELTS'));
const storage=foundationApi.createMemoryStorage();
storage.setItem('ovidhan_ielts_diagnostic_v2',JSON.stringify({correct:0,weakestKey:'grammar'}));
const learning=foundationApi.createLearningFoundation({localStorage:storage,sessionStorage:foundationApi.createMemoryStorage(),now:()=>new Date('2026-08-22T12:00:00Z')});
assert.deepEqual(learning.getState().skillEvidence,{});
assert.equal(learning.recordSkillEvidence('ielts-diagnostic-v1:q01','essay_thesis_focus','DIAGNOSTIC_OBJECTIVE','incorrect','ielts-diagnostic-v1'),true);
assert.equal(learning.recordSkillEvidence('ielts-diagnostic-v1:q01','essay_thesis_focus','DIAGNOSTIC_OBJECTIVE','correct','ielts-diagnostic-v1'),true);
const evidence=learning.getState().skillEvidence['ielts-diagnostic-v1:q01'];
assert.equal(Object.keys(learning.getState().skillEvidence).length,1);
assert.equal(evidence.attempts,2);
assert.deepEqual(learning.getState().mistakeSignals,{});
assert.ok(!('repairResult' in evidence)&&!('retestResult' in evidence)&&!('masteryStatus' in evidence));
assert.deepEqual(Object.keys(evidence).sort(),['attempts','evidence_id','evidence_type','first_seen_at','last_seen_at','result','skill_id','source_id']);
assert.doesNotMatch(read('learning-foundation.js'),/ovidhan_ielts_(?!diagnostic_v2)/);
const frozen=require('../reports/ovidhan-learning-foundation-3b-frozen-hashes.json');
assert.equal(frozen.aggregateSha256,'202cc8c85317ff57756c7167b1bfb1c99f784497525f3fb633d2c81757148ce0');
frozen.pages.forEach(page=>assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,page.path))).digest('hex'),page.sha256));
frozen.guards.forEach(guard=>assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,guard.path))).digest('hex'),guard.sha256));
console.log(JSON.stringify({status:'PASS',questions:40,mapped:mapped.length,unmapped:unmapped.length,uniqueMappedSkills:new Set(mapped.map(item=>item.primary_skill_id)).size,questionSetSha256,graph:{families:14,skills:65,active:65,practiceMappings:240},legacyCreatesEvidence:false,distinctEvidenceAfterRetake:1,frozenAggregateSha256:frozen.aggregateSha256},null,2));
